version: '3.8'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 6789:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    restart: unless-stopped
